### ISSUE TITLE
getSavedScanAPI

### ISSUE THREAD

**Issue by apurvabisht97** [Sunbird-Saral/Project-Saral#26]
-> currently token used here is basicAuth .

**Comment by dileep-gadiraju** [comment]
Clarification reg. /getSavedScan API.
As you can see in Postman Collection and Swagger documentation (refer below screenshots) of /getSavedScan API, 
it accepts Basic Auth which expects username/password instead of bearer token. 
This is specific to this particular API and the reason is, apart from the frontend Saral App this API (/getSavedScan) may be used by other Apps or jobs to fetch saved scan details to process or push to CCube database.

Reference backend implementation for Basic Auth you can find it here - https://github.com/Sunbird-Saral/Project-Saral/blob/v1.0.0-beta.1/v1.0/backend/src/middleware/auth.js#L22-L34

PostMan Collection:
getSavedScan_postmancollection_screenshot.png

Swagger Documentation Reference:
https://github.com/Sunbird-Saral/Project-Saral/blob/v1.0.0-beta.1/specs/v1/swagger-saral-apidoc.yaml#L316-L317
swaggerdoc_screenshot.png
