### ISSUE TITLE
Periodic Background data push from Saral App to backend

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#45]
**Periodic Background data push from Saral App to backend.**

- Periodic background job within Saral App should poll local storage 
- If data is present in local storage, check the connectivity and push the data.
- if there is a failure pushing data in the background, proper logs should be written for troubleshooting later.
- We should make sure if the background data push fails, local storage data is not lost.
- We should make sure there is no conflict between manual Save All action and background job. Maybe by using locking.
- Top section of the app should show an upload icon across the pages when backend data push is in progress. 

**Frequency and criteria of background job:**

1. Every 30 mins job has to check the below criteria before pushing data.
2. Minimum of 10 records should be in local storage.

**Comment by dileep-gadiraju** [comment]
@navin9584 ,

please propose technically how to implement:

1) Background Jobs
2) Lock the local storage

**Comment by apurvabisht97** [comment]
if user tries to logout when we have scanned the sheet it should ask user to wait as background process is going on .

**Comment by apurvabisht97** [comment]
this issue is resolved and the test cases of this issue is below:-
timer which we have implemented is for 10 minute .
1. once you login to app your background job timer will start once you scan more than 10 students or if you already have 10 or more students in your local storage background job wil automatically push it to backend.
2. when backgorund job will starting pushing your data to backend you will get one notification that your data is uploading and once it is uploaded you will get second notification that your data is uploaded.
3. when backgorund job starts you cannot do other process like if you try to logout it will not allow you to logout . it will give alert message "Data is uploading please wait till it finished."
4. Once you data is uploaded to backend and you get your second notification then you will be able to logout .
5. when background job starts you cannot do other process like if you try to click on save all scan it will not allow you to save it . it will give alert message "Data is uploading please wait till it finished."
6. If you try to scan sheet and try to submit it but your background job is already started at that time you will not allow to submit it .you will get one alert message "Data is uploading please wait till it finished."
7. if your background jobs starts but if you backend api will return the response faster then you you will face error "Something went wrong with background process, please contact Admin"
